# How to lead <!-- act{#cde-design-model} -->
Een Landmacht is bij uitstek een organisatie om te leren van en over leiderschap. De militair heeft een fysiek en mentaal veeleisend beroep onder soms extreme omstandigheden. De militair officier [^officier] moet daarom in verschillende situaties leiding kunnen geven en ontvangen. De verschillende vormen van leidinggeven lopen als een rode draad door de loopbaan van de officier. Het Defensie Leiderschapskompas geeft houvast aan de professional die leiderschap neemt over zichzelf en zijn omgeving.

Het Commando Landstrijdkrachten streeft naar nieuwe manieren om relevante innovatie bij de Landmacht integraal met externe partijen uit te voeren in het tempo van de markt. De omstandigheden waaronder we willen innoveren in het landoptreden zijn vluchtig, onzeker, complex en ambigu [^vuca]. Deze innovatie context vraagt --net als de militaire context-- steeds meer gespecialiseerde kennis, unieke vaardigheid en een reflecterende attitude van de professional. Het Defensie Leiderschapskompas geeft houvast aan de professional die leiderschap neemt over zichzelf, een context of vraagstuk. In dit hoofdstuk beschrijven we het leiderschapskompas aangepast op de context van Military Design & Innovation.

[^officier]: binnen de profielschets Krijgsmacht officier lezen we voor de militair officier ook de burger gelijkgestelde medewerker.
[^vuca]: de profielschets Krijgsmacht officier noemt dit een Volatile, Uncertain, Complex, Ambiguous environment (VUCA)

<!--
Dit hoofdstuk beschrijft een aantal veel gebruikte en doorontwikkelde handelingsperspectieven om gezamenlijk een idee of ambitie te verwezenlijken.
Inspiratie voor deze handelingsperspectieven komen van verschillende vakgebieden zoals netwerk- en ketenregie, design-research, aliantiekunde, militaire doctrines, innovatiekunde, engineering, natuurkunde, en militaire inlichtingen. De handelingsperspectieven zijn verwerkt tot technieken en tools van de craftsman en beschreven in dit hoofdstuk.
-->

# Defensie leiderschapskompas
"Leiders van nu hebben karakter én vaardigheden. Ze kunnen snel, effectief en bewust hun leiderschapsstijl aanpassen aan wat de situatie op dat moment vraagt. Bovendien kennen ze de beperkingen van hun voorkeursstijl en blijven ze leren, van zichzelf én van anderen."[@ministerie_van_defensie_visie_2015, p3]

"Karakter (zijn) en gedrag (doen) zijn kernelementen van leidinggeven. Het leiderschapskompas geeft weer wat binnen Defensie als gewenst karakter en gedrag wordt ervaren. Het gewenste karakter en het gewenste gedrag staan op zichzelf niet garant voor succes. Ook het aanpassen aan en inspelen op de situatie en het willen verbeteren (leren) is noodzakelijk. Defensie schrijft dan ook niet één leiderschapstheorie of stijl voor, maar doet een beroep op je leervermogen en je reflectievermogen. Goed leidinggeven is doen wat nodig is. Kennis over jezelf, de ander, het team en de bredere context zorgen ervoor dat je op het juiste moment doet wat nodig is."[@ministerie_van_defensie_visie_2015, p7]

## karakter (zijn)
Leiderschap bij Defensie gaat over zijn, doen en leren. De vier karaktereigenschappen uit de leiderschapskompas gelden ook binnen de Military Design & Innovation context.

> MOEDIG
> Je wordt gekarakteriseerd als iemand die (ook in moeilijke situaties) staat voor wat goed is. Ergens voor staan betekent kwetsbaar zijn en dat vergt moed. Je bent iemand die op staat wanneer anderen blijven zit- ten en die eigen angsten trotseert. Je gaat confrontaties aan met het risico op tegenslag, onzekerheid of zelfs verwonding en levensgevaar. Je neemt waar nodig impopulaire maatregelen, doorbreekt vaste gewoontes en gaat gevoelige onderwerpen niet uit de weg.

```
EERLIJK
Je wordt gekarakteriseerd als iemand die de waarheid spreekt en daarbij mensen in hun waarde laat. Je zegt wat je denkt en doet wat je zegt. Je speelt open kaart en geeft fouten toe. Je handelt naar eer en geweten, in overeenstemming met persoonlijke waarden en algemeen geldende normen en regels.
```

VERANTWOORDELIJK
Je wordt gekarakteriseerd als iemand die aanspreek- baar is op het eigen handelen en dat van het team en de gevolgen daarvan. Je houdt rekening met de invloed van eigen besluiten op processen en personen. Je doet wat je kunt en houdt je aan afspraken. Je waakt over de belangen van Defensie en geeft in houding, voorkomen en gedrag het goede voorbeeld.

DIENSTBAAR
Je wordt gekarakteriseerd als iemand die zichzelf
ten dienste stelt van het team en de taak, waarbij je
je eigen belang ondergeschikt maakt aan het team,
de organisatie en de samenleving. Je creëert de omstandigheden waaronder je medewerkers optimaal presteren en groeien.

## regisseren
Deze paragraaf 'regisseren' zal gaan over verschillende vormen om de relevante activiteiten parallel en/of volgordelijk te laten verlopen. Oftewel het regisseren van een traject, project en programma. Ook een korte toelichting op de verschillen tussen traject, project en programma worden toegevoegd.

> onder constructie: traject- en procesregie en projectbegeleiding.






### begeleiden en faciliteren
De belangrijkste diensten van de afdeling Innovatie (io) zijn het begeleiden van de Landmacht-professionals bij het innoveren in hun vak en van hun vakmanschap. Daarom neemt de afdeling Innovatie (io) geen primair eigenaarschap in de programma's of projecten maar steunt de opdrachtgever, -nemer en overige betrokkenen in het gehele traject tot implementatie en escaleert naar de juiste niveaus waar nodig.




## orchestreren
Het Ministerie Defensie schetste toekomstscenario's en formuleerde ambities en inrichtingsprincipes. De Koninklijke Landmacht beschreef een visie en ontwikkellijnen. Het is aan kennisadviseurs, kenniswerkers en subject matter experts om daarbinnen ambities, operationele wensen en behoeften, technologische ontwikkelingen en inventies te programmeren.

#### rollen
Het beschrijven van context, selecteren van activiteiten en betrekken van partners is eerder een kunst dan wetenschap. Deze kunst is het craftmanship van trajectbegeleiders, programma-managers en SBID-medewerkers. De verschillende rollen die bijdragen in een traject worden hier -in een later moment- beschreven. De kwaliteiten en kwalificaties van deze rollen volgen uit de doorontwikkeling Military Design & Innovation 2021.

##### trajectbegeleider {-}
##### programma-manager {-}
##### SBID-medewerker {-}
##### opdrachtgever {-}
##### opdrachtnemer {-}
